name: My-Git_Test-Action
env:
  MyName  : "Malediq"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello
      run: echo "Hello World T"
      
    - name: Some commands
      run: |
        echo "1"
        echo "2"
        echo "${{ env.MyName }}"
        
  deploy:
    runs-on: ubuntu-latest
    needs: [testing]
    
    steps:
    - name: Print Hello
      run: echo "Hello World D"
      
  
